// Uni-one — мок-данные прототипа.
// Реальные клубы и события из презентации команды (ДМ_команда 1).

export const CATEGORIES = [
  { id: "music", label: "Музыка", icon: "🎸", color: "#e8a33d" },
  { id: "lang", label: "Языки", icon: "☕", color: "#3d9be8" },
  { id: "games", label: "Интеллект. игры", icon: "♟️", color: "#8e6fd6" },
  { id: "sport", label: "Спорт", icon: "🏓", color: "#3dc97a" },
  { id: "science", label: "Наука", icon: "🔬", color: "#e85d75" },
  { id: "speaking", label: "Ораторика", icon: "🎤", color: "#d6a13d" },
  { id: "assoc", label: "Ассоциации", icon: "🤝", color: "#5d7de8" },
];

export const catById = (id) => CATEGORIES.find((c) => c.id === id) || CATEGORIES[0];

// Интересы для онбординга (поиск «своих»)
export const INTERESTS = [
  { id: "music", label: "Музыка", emoji: "🎶" },
  { id: "boardgames", label: "Настолки", emoji: "🎲" },
  { id: "cinema", label: "Кино", emoji: "🎬" },
  { id: "startups", label: "Стартапы", emoji: "🚀" },
  { id: "english", label: "Английский", emoji: "🇬🇧" },
  { id: "chess", label: "Шахматы", emoji: "♟️" },
  { id: "quiz", label: "Квизы", emoji: "🧠" },
  { id: "science", label: "Наука", emoji: "🔬" },
  { id: "speaking", label: "Выступления", emoji: "🎤" },
  { id: "sport", label: "Спорт", emoji: "🏓" },
  { id: "volunteer", label: "Волонтёрство", emoji: "💚" },
  { id: "art", label: "Творчество", emoji: "🎨" },
];

// События ближайшей недели (модуль «Афиша»)
export const EVENTS = [
  {
    id: "e1",
    title: "Вечерняя гитара",
    category: "music",
    org: "Музыкальная ассоциация",
    date: "2026-06-08",
    time: "19:00",
    place: "Корпус факультета, «зелёная стена»",
    forNewbies: true,
    spots: 30,
    taken: 21,
    desc: "Ежемесячный квартирник с живой музыкой, чаем и уютной атмосферой прямо в корпусе. Приходи послушать или сыграть сам.",
  },
  {
    id: "e2",
    title: "7 o'clock tea — разговорный клуб",
    category: "lang",
    org: "Английский клуб",
    date: "2026-06-08",
    time: "19:00",
    place: "Ауд. 311",
    forNewbies: true,
    spots: 16,
    taken: 9,
    desc: "Встречи для практики английского в непринуждённой обстановке за чашкой чая. Любой уровень welcome.",
  },
  {
    id: "e3",
    title: "Шахматный турнир",
    category: "games",
    org: "Шахматный клуб",
    date: "2026-06-09",
    time: "18:30",
    place: "Зона отдыха, 2 этаж",
    forNewbies: true,
    spots: 24,
    taken: 12,
    desc: "Для игроков любого уровня — от новичков до опытных стратегов. Блиц и классика, разбор партий.",
  },
  {
    id: "e4",
    title: "«Эконом говорит» — мастер-класс по выступлениям",
    category: "speaking",
    org: "Ораторский клуб",
    date: "2026-06-10",
    time: "17:00",
    place: "Большая аудитория",
    forNewbies: false,
    spots: 50,
    taken: 38,
    desc: "Тренинг по публичным выступлениям и встреча с приглашённым спикером. Учимся не бояться сцены.",
  },
  {
    id: "e5",
    title: "Музыкальный час: вечер джаза",
    category: "music",
    org: "Музыкальная ассоциация",
    date: "2026-06-11",
    time: "19:30",
    place: "Актовый зал",
    forNewbies: true,
    spots: 80,
    taken: 44,
    desc: "Тематический музыкальный вечер, где выступают сами студенты и преподаватели. В программе — джаз и саундтреки.",
  },
  {
    id: "e6",
    title: "«Что? Где? Когда?» — командный турнир",
    category: "games",
    org: "Интеллектуальный клуб",
    date: "2026-06-12",
    time: "18:00",
    place: "Ауд. 405",
    forNewbies: true,
    spots: 60,
    taken: 51,
    desc: "Командные интеллектуальные игры. Нет команды? Запишись соло — поможем собрать состав на месте.",
  },
  {
    id: "e7",
    title: "Лекция «Экономика за жизнь»",
    category: "science",
    org: "Совет молодых учёных",
    date: "2026-06-13",
    time: "16:00",
    place: "Ауд. 201",
    forNewbies: false,
    spots: 100,
    taken: 27,
    desc: "Цикл лекций и семинаров для тех, кому интересна наука. Разбираем экономику простым языком.",
  },
  {
    id: "e8",
    title: "Настольный теннис: открытая запись",
    category: "sport",
    org: "Спортклуб",
    date: "2026-06-13",
    time: "15:00",
    place: "Спортзал",
    forNewbies: true,
    spots: 16,
    taken: 6,
    desc: "Свободные игры в настольный теннис и нарды. Ракетки и инвентарь на месте, опыт не нужен.",
  },
];

// Сообщества по интересам (модуль «Сообщества»)
export const COMMUNITIES = [
  {
    id: "c1",
    name: "Настольный движ",
    tags: ["boardgames"],
    members: 142,
    online: 12,
    desc: "Манчкин, Каркассон, Диксит каждую среду. Ищем своих за столом.",
    lastMsg: "Аня: кто сегодня на партейку в 18:00? 🎲",
  },
  {
    id: "c2",
    name: "Киноклуб «Эконом смотрит»",
    tags: ["cinema"],
    members: 208,
    online: 23,
    desc: "Совместные просмотры и обсуждения — от классики до артхауса.",
    lastMsg: "Макс: в пятницу показываем «Большой куш», го",
  },
  {
    id: "c3",
    name: "Стартап-движение",
    tags: ["startups"],
    members: 96,
    online: 8,
    desc: "Питчи, поиск кофаундеров, пятничные демо-дни. От идеи до MVP.",
    lastMsg: "Эдуард: ищу человека на фронт в проект ☝️",
  },
  {
    id: "c4",
    name: "English Speaking Hub",
    tags: ["english"],
    members: 174,
    online: 19,
    desc: "Чат на английском, разговорные пары и подготовка к 7 o'clock tea.",
    lastMsg: "Polina: let's practice before Sunday! ☕",
  },
  {
    id: "c5",
    name: "Шахматы & стратегии",
    tags: ["chess"],
    members: 88,
    online: 5,
    desc: "Разборы партий, онлайн-турниры, подготовка к клубным встречам.",
    lastMsg: "Руслан: кто разберёт мою партию? выложил pgn",
  },
  {
    id: "c6",
    name: "Квиз-команда «Совы»",
    tags: ["quiz"],
    members: 64,
    online: 7,
    desc: "Собираем состав на «Что? Где? Когда?» и городские квизы.",
    lastMsg: "Амина: нужен ещё один игрок на четверг! 🧠",
  },
];

// Стартовый профиль пользователя (геймификация)
export const INITIAL_USER = {
  name: "Максим",
  isNewbie: true,
  joinedDays: 3,
  interests: [],
  xp: 40,
  level: 1,
  badges: [
    { id: "b_join", icon: "🌱", label: "Первый шаг", earned: true },
    { id: "b_first_event", icon: "🎟️", label: "Первое событие", earned: false },
    { id: "b_community", icon: "🤝", label: "Нашёл своих", earned: false },
    { id: "b_explorer", icon: "🧭", label: "Исследователь", earned: false },
    { id: "b_streak", icon: "🔥", label: "3 события подряд", earned: false },
  ],
};

export const LEVELS = [0, 100, 250, 450, 700]; // XP-порог для каждого уровня
