// Uni-one — мок-данные прототипа (симбиоз знакомств и мероприятий).
// Фото подгружаются с pravatar.cc / picsum.photos — при отсутствии сети
// показывается градиентный фон-заглушка.

export const avatar = (n) => `https://i.pravatar.cc/600?img=${n}`;
export const banner = (seed) => `https://picsum.photos/seed/${seed}/900/600`;

// Категории мероприятий (фильтры)
export const EVENT_CATEGORIES = [
  { id: "party", label: "Вечеринки", icon: "🎉" },
  { id: "networking", label: "Нетворкинг", icon: "🤝" },
  { id: "lecture", label: "Лекции", icon: "🎓" },
  { id: "sport", label: "Спорт", icon: "🏆" },
  { id: "music", label: "Музыка", icon: "🎵" },
  { id: "culture", label: "Культура", icon: "🎭" },
  { id: "it", label: "IT", icon: "💻" },
  { id: "games", label: "Игры", icon: "🎲" },
];
export const catLabel = (id) =>
  EVENT_CATEGORIES.find((c) => c.id === id)?.label || id;
export const catIcon = (id) =>
  EVENT_CATEGORIES.find((c) => c.id === id)?.icon || "🎟️";

// Текущий пользователь (профиль)
export const ME = {
  name: "Анна Соколова",
  age: 20,
  uni: "МГУ",
  faculty: "ВМК",
  course: "3 курс",
  photo: avatar(47),
  bio: "Люблю решать сложные задачи и искать красивые алгоритмы не только в коде, но и в жизни. Обожаю походы в кино и прогулки по Москве. Всегда за новые знакомства и интересные разговоры!",
  interests: ["Программирование", "Кино", "Спорт", "Музыка"],
  eventInterests: ["party", "music", "it", "games"],
  stats: { likes: 124, matches: 38, friends: 12 },
};

// Мероприятия (экран «Мероприятия»)
export const EVENTS = [
  {
    id: "e1",
    title: "Вечер настолок МГУ",
    category: "games",
    badge: "hot",
    date: "Сегодня",
    time: "18:00",
    place: "Кампус МГУ, клубная зона",
    going: 42,
    seed: "boardgames99",
    today: true,
    online: false,
    attendees: [12, 45, 15],
    desc: "Самый тёплый вечер недели! Манчкин, Каркассон, Codenames и десятки других игр. Приходи один или с друзьями — поможем собрать компанию за столом. Чай и печеньки за счёт клуба.",
  },
  {
    id: "e2",
    title: "Хакатон «Цифровой МГУ»",
    category: "it",
    badge: "new",
    date: "14 июня",
    time: "10:00",
    place: "Физический факультет МГУ",
    going: 120,
    seed: "hackathon42",
    today: false,
    online: false,
    attendees: [32, 33, 20],
    desc: "48 часов, чтобы собрать продукт мечты. Призовой фонд, менторы из IT-компаний и нетворкинг с лучшими студентами. Регистрируйся командой или найди сокомандников прямо здесь.",
  },
  {
    id: "e3",
    title: "Speed Dating МГУ",
    category: "party",
    badge: "new",
    date: "21 июня",
    time: "19:00",
    place: "Студенческий центр МГУ",
    going: 61,
    seed: "speeddating7",
    today: false,
    online: false,
    attendees: [47, 45, 20],
    desc: "5 минут на знакомство — и дальше решаешь ты. Лёгкий формат, приятная атмосфера и реальный шанс встретить своего человека из соседнего корпуса.",
  },
  {
    id: "e4",
    title: "English Speaking Club",
    category: "lecture",
    badge: null,
    date: "Сегодня",
    time: "19:00",
    place: "Онлайн · Zoom",
    going: 28,
    seed: "english23",
    today: true,
    online: true,
    attendees: [15, 12, 32],
    desc: "Разговорный клуб для любого уровня. Обсуждаем кино, путешествия и науку на английском в дружелюбной обстановке. Ссылка на Zoom придёт после записи.",
  },
  {
    id: "e5",
    title: "Кинопоказ под открытым небом",
    category: "culture",
    badge: "hot",
    date: "9 июня",
    time: "21:30",
    place: "Парк МГУ",
    going: 87,
    seed: "cinema15",
    today: false,
    online: false,
    attendees: [20, 33, 45],
    desc: "Большой экран, пледы, попкорн и звёздное небо. В программе — культовая классика. Бери друзей или знакомься с новыми прямо на пледе рядом.",
  },
  {
    id: "e6",
    title: "Вечеринка первокурсников",
    category: "party",
    badge: "hot",
    date: "15 июня",
    time: "22:00",
    place: "Клуб «Высота», Москва",
    going: 210,
    seed: "party88",
    today: false,
    online: false,
    attendees: [49, 13, 26],
    desc: "Главная вечеринка сезона! DJ-сет, фотозона и сотни новых лиц. Идеальный повод познакомиться со всем потоком за один вечер.",
  },
  {
    id: "e7",
    title: "Турнир по баскетболу 3х3",
    category: "sport",
    badge: null,
    date: "12 июня",
    time: "16:00",
    place: "Спорткомплекс МГУ",
    going: 54,
    seed: "basketball3",
    today: false,
    online: false,
    attendees: [12, 51, 33],
    desc: "Собирай команду из трёх человек или приходи один — поможем добрать состав. Призы победителям и заряд драйва всем участникам.",
  },
  {
    id: "e8",
    title: "Лекция «ИИ и будущее профессий»",
    category: "lecture",
    badge: "new",
    date: "18 июня",
    time: "17:00",
    place: "Главное здание МГУ, ауд. 01",
    going: 96,
    seed: "ailecture",
    today: false,
    online: false,
    attendees: [15, 20, 32],
    desc: "Приглашённый спикер из крупной IT-компании расскажет, как ИИ меняет рынок труда и какие навыки прокачивать уже сейчас. После — Q&A и нетворкинг.",
  },
  {
    id: "e9",
    title: "Джазовый вечер",
    category: "music",
    badge: null,
    date: "20 июня",
    time: "20:00",
    place: "Арт-кафе на Моховой",
    going: 73,
    seed: "jazz11",
    today: false,
    online: false,
    attendees: [45, 26, 13],
    desc: "Живой джаз, приглушённый свет и уютная атмосфера. Выступают студенты и преподаватели консерватории. Идеально для неспешного знакомства.",
  },
  {
    id: "e10",
    title: "Karaoke Night МГУ",
    category: "music",
    badge: "hot",
    date: "Сегодня",
    time: "21:00",
    place: "Студклуб МГУ",
    going: 64,
    seed: "karaoke5",
    today: true,
    online: false,
    attendees: [49, 12, 20],
    desc: "Бери микрофон и зажигай! Хиты всех времён, дружелюбная публика и нулевой порог стеснения. Лучший способ влиться в компанию.",
  },
  {
    id: "e11",
    title: "Нетворкинг «IT-карьера»",
    category: "networking",
    badge: "new",
    date: "16 июня",
    time: "18:30",
    place: "Онлайн · Telegram",
    going: 132,
    seed: "networking8",
    today: false,
    online: true,
    attendees: [33, 51, 15],
    desc: "Встреча с рекрутерами и тимлидами топовых компаний. Узнай, как попасть на стажировку, и обменяйся контактами с такими же амбициозными студентами.",
  },
  {
    id: "e12",
    title: "Выставка студенческого искусства",
    category: "culture",
    badge: null,
    date: "13 июня",
    time: "12:00",
    place: "Галерея на Воробьёвых горах",
    going: 41,
    seed: "artexpo",
    today: false,
    online: false,
    attendees: [45, 20, 26],
    desc: "Картины, фотография и инсталляции от студентов МГУ. Вход свободный, гид по экспозиции и тёплая творческая атмосфера.",
  },
  {
    id: "e13",
    title: "Забег «Кросс наций»",
    category: "sport",
    badge: null,
    date: "Сегодня",
    time: "09:00",
    place: "Набережная МГУ",
    going: 188,
    seed: "running9",
    today: true,
    online: false,
    attendees: [12, 32, 51],
    desc: "Массовый утренний забег на 3 и 5 км. Бежим в своём темпе, заряжаемся энергией и знакомимся на финише за стаканом чая.",
  },
  {
    id: "e14",
    title: "Квиз «Что? Где? Когда?»",
    category: "games",
    badge: "new",
    date: "19 июня",
    time: "18:00",
    place: "Ауд. 405, 2-й корпус",
    going: 67,
    seed: "quiz44",
    today: false,
    online: false,
    attendees: [20, 45, 33],
    desc: "Командные интеллектуальные игры. Нет команды? Запишись соло — поможем собрать состав на месте. Победителей ждут призы.",
  },
];

export const eventById = (id) => EVENTS.find((e) => e.id === id);

// Анкеты для свайпов (экран «Главная»). events — куда человек идёт.
export const PEOPLE = [
  {
    id: "p1",
    name: "Максим",
    age: 21,
    faculty: "ВМК",
    course: "3 курс",
    distance: "500 м",
    photo: avatar(12),
    verified: true,
    likesYou: true,
    bio: "Пишу на Python и играю в футбол по выходным. Ищу компанию на хакатоны и вечерний кофе.",
    interests: ["Программирование", "Кофе", "Футбол", "Музыка", "Путешествия", "Кино"],
    events: ["e2", "e1", "e11"],
  },
  {
    id: "p2",
    name: "Лиза",
    age: 19,
    faculty: "Журфак",
    course: "2 курс",
    distance: "1.2 км",
    photo: avatar(45),
    verified: false,
    likesYou: false,
    bio: "Снимаю на плёнку, обожаю старое кино и уютные книжные. Расскажи мне свой любимый фильм.",
    interests: ["Кино", "Фотография", "Литература", "Кофе"],
    events: ["e5", "e12"],
  },
  {
    id: "p3",
    name: "Игорь",
    age: 22,
    faculty: "Физфак",
    course: "4 курс",
    distance: "300 м",
    photo: avatar(15),
    verified: true,
    likesYou: true,
    bio: "Физик-теоретик, шахматист и меломан. За интеллектуальные споры до утра.",
    interests: ["Наука", "Шахматы", "Музыка", "Спорт"],
    events: ["e14", "e8", "e9"],
  },
  {
    id: "p4",
    name: "Саша",
    age: 20,
    faculty: "Экономфак",
    course: "3 курс",
    distance: "800 м",
    photo: avatar(32),
    verified: false,
    likesYou: false,
    bio: "Запускаю свой стартап и бегаю по утрам. Практикую английский — let's chat!",
    interests: ["Стартапы", "Английский", "Бег", "Кофе"],
    events: ["e11", "e13", "e4"],
  },
  {
    id: "p5",
    name: "Настя",
    age: 19,
    faculty: "Истфак",
    course: "1 курс",
    distance: "2.1 км",
    photo: avatar(20),
    verified: true,
    likesYou: true,
    bio: "Первокурсница, влюблена в искусство и путешествия. Покажи мне любимые места Москвы!",
    interests: ["Искусство", "Путешествия", "Музыка", "Кино"],
    events: ["e12", "e6", "e9"],
  },
  {
    id: "p6",
    name: "Дима",
    age: 23,
    faculty: "Мехмат",
    course: "магистратура",
    distance: "650 м",
    photo: avatar(33),
    verified: false,
    likesYou: false,
    bio: "Математик с гитарой. Катаюсь на велике по набережным и варю отличный кофе.",
    interests: ["Математика", "Гитара", "Велоспорт", "Кофе"],
    events: ["e10", "e9", "e13"],
  },
  {
    id: "p7",
    name: "Катя",
    age: 20,
    faculty: "Соцфак",
    course: "2 курс",
    distance: "1.5 км",
    photo: avatar(44),
    verified: true,
    likesYou: true,
    bio: "Организую студенческие вечеринки и обожаю караоке. Жизнь — это люди вокруг!",
    interests: ["Вечеринки", "Караоке", "Танцы", "Психология"],
    events: ["e6", "e10", "e3"],
  },
  {
    id: "p8",
    name: "Артём",
    age: 22,
    faculty: "ВМК",
    course: "4 курс",
    distance: "400 м",
    photo: avatar(13),
    verified: false,
    likesYou: false,
    bio: "Баскетбол, код и хорошая музыка. Ищу команду на турнир 3х3 и на хакатон.",
    interests: ["Баскетбол", "Программирование", "Музыка", "Спорт"],
    events: ["e7", "e2", "e8"],
  },
];

// Диалоги (экран «Сообщения»)
export const CHATS = [
  { id: "c1", name: "Настя", photo: avatar(20), last: "Привет! Как прошёл твой день?", time: "14:30", unread: 2, online: true },
  { id: "c2", name: "Дима", photo: avatar(33), last: "Ты на лекции по программированию?", time: "12:45", unread: 1, online: true },
  { id: "c3", name: "Катя", photo: avatar(44), last: "Спасибо за рекомендации! 🙌", time: "11:20", unread: 0, online: true },
  { id: "c4", name: "Артём", photo: avatar(13), last: "Давай завтра после пар?", time: "Вчера", unread: 3, online: false },
];

// Стартовые сообщения в открытом диалоге
export const THREAD = {
  c1: [
    { from: "them", text: "Привет! Как прошёл твой день?", time: "14:30" },
    { from: "me", text: "Привет! Отлично, сдала проект 🎉", time: "14:32" },
    { from: "them", text: "Поздравляю! Отметим на вечере настолок?", time: "14:33" },
  ],
  c2: [
    { from: "them", text: "Ты на лекции по программированию?", time: "12:45" },
    { from: "me", text: "Да, во втором ряду 👋", time: "12:50" },
  ],
  c3: [{ from: "them", text: "Спасибо за рекомендации! 🙌", time: "11:20" }],
  c4: [{ from: "them", text: "Давай завтра после пар?", time: "Вчера" }],
};

// «Поиск знакомых» — рекомендации
export const SUGGESTIONS = [
  { id: "s1", name: "Виктория Смирнова", faculty: "Факультет журналистики", mutual: 12, photos: [49, 45, 20], photo: avatar(26) },
  { id: "s2", name: "Егор Кузнецов", faculty: "Факультет информатики", mutual: 8, photos: [12, 15, 33], photo: avatar(51) },
];

// Базовые уведомления (помимо динамических мэтчей)
export const NOTIFICATIONS = [
  { id: "n3", type: "event", text: "Сегодня «Вечер настолок МГУ» в 18:00", time: "3 ч назад", photo: banner("boardgames99") },
  { id: "n4", type: "message", text: "Настя отправила вам сообщение", time: "Вчера", photo: avatar(20) },
  { id: "n5", type: "friend", text: "Егор принял вашу заявку в друзья", time: "Вчера", photo: avatar(51) },
];

// Круги общения (классификация контактов)
export const CIRCLES = [
  { id: "friend", label: "Друзья", icon: "💚", color: "var(--green)" },
  { id: "pal", label: "Приятели", icon: "👋", color: "var(--blue)" },
  { id: "acq", label: "Знакомые", icon: "🙂", color: "var(--muted)" },
];
export const circleById = (id) => CIRCLES.find((c) => c.id === id) || CIRCLES[2];
// Близкий круг — для раздела «где мои друзья»
export const CLOSE_CIRCLES = ["friend", "pal"];

// Контакты пользователя (с кругом общения и мероприятиями)
export const CONTACTS = [
  { id: "p1", name: "Максим", age: 21, faculty: "ВМК", photo: avatar(12), circle: "pal", events: ["e1", "e2", "e11"], bio: "Пишу на Python и играю в футбол по выходным.", interests: ["Программирование", "Кофе", "Футбол"] },
  { id: "p3", name: "Игорь", age: 22, faculty: "Физфак", photo: avatar(15), circle: "friend", events: ["e14", "e8", "e9"], bio: "Физик-теоретик, шахматист и меломан.", interests: ["Наука", "Шахматы", "Музыка"] },
  { id: "p5", name: "Настя", age: 19, faculty: "Истфак", photo: avatar(20), circle: "friend", events: ["e1", "e6", "e9"], bio: "Влюблена в искусство и путешествия.", interests: ["Искусство", "Путешествия", "Музыка"] },
  { id: "p7", name: "Катя", age: 20, faculty: "Соцфак", photo: avatar(44), circle: "pal", events: ["e6", "e10", "e3"], bio: "Организую студенческие вечеринки.", interests: ["Вечеринки", "Караоке", "Танцы"] },
  { id: "p8", name: "Артём", age: 22, faculty: "ВМК", photo: avatar(13), circle: "pal", events: ["e7", "e2", "e8"], bio: "Баскетбол, код и хорошая музыка.", interests: ["Баскетбол", "Программирование", "Музыка"] },
  { id: "k1", name: "Дима", age: 23, faculty: "Мехмат", photo: avatar(33), circle: "friend", events: ["e10", "e13", "e9"], bio: "Математик с гитарой и велосипедом.", interests: ["Математика", "Гитара", "Велоспорт"] },
  { id: "p2", name: "Лиза", age: 19, faculty: "Журфак", photo: avatar(45), circle: "acq", events: ["e5", "e12"], bio: "Снимаю на плёнку, обожаю старое кино.", interests: ["Кино", "Фотография", "Литература"] },
  { id: "p4", name: "Саша", age: 20, faculty: "Экономфак", photo: avatar(32), circle: "acq", events: ["e11", "e13", "e4"], bio: "Запускаю стартап и бегаю по утрам.", interests: ["Стартапы", "Английский", "Бег"] },
];

